on:
  push:
    branches:
      - master




jops:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: "testing github action"
        run: pwd
      - name: "testing print"
        run: echo Ahmed
